In [0]:
#Importing Libraries, Implementing Kernel SVM with Scikit-Learn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Importing the Dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [0]:
# Preprocessing
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [131]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
print (X_train)

     sepal-length  sepal-width  petal-length  petal-width
105           7.6          3.0           6.6          2.1
61            5.9          3.0           4.2          1.5
90            5.5          2.6           4.4          1.2
113           5.7          2.5           5.0          2.0
77            6.7          3.0           5.0          1.7
..            ...          ...           ...          ...
15            5.7          4.4           1.5          0.4
76            6.8          2.8           4.8          1.4
12            4.8          3.0           1.4          0.1
19            5.1          3.8           1.5          0.3
126           6.2          2.8           4.8          1.8

[120 rows x 4 columns]


In [132]:
# Training the Algorithm
# To train the kernel SVM, we use the same SVC class of the Scikit-Learn's svm library. The difference lies in the value for the kernel parameter of the SVC class.
#  for kernel SVM you can use Gaussian, polynomial, sigmoid, or computable kernel.
from sklearn.svm import SVC
#svclassifier = SVC(kernel='poly', degree=3)
#svclassifier = SVC(kernel='sigmoid')
svclassifier = SVC(kernel='linear')

svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [133]:
# Making Predictions & evaluation
y_pred = svclassifier.predict(X_test)

# Evaluating the Algorithm

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0  8  1]
 [ 0  0  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.89      0.94         9
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        30
      macro avg       0.97      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30

